### ISSUE TITLE
NotImplementError

### ISSUE THREAD

**Issue by rouchoo** [lovelyyoshino/RHACrackNet#1]
when i try to run main.py, i encounter this probelm. Can you tell me how to solve it?

![2078235639](https://github.com/lovelyyoshino/RHACrackNet/assets/43592098/84060d92-3f11-4dca-8719-f8f209e36611)

**Comment by lovelyyoshino** [comment]
you must write as ：python main.py  ./config/unet_CamCrack789.yaml
