### ISSUE TITLE
Experimental results

### ISSUE THREAD

**Issue by XZNWU** [lovelyyoshino/RHACrackNet#2]
Thank you very much for providing the code. We used the code you provided, but the experimental results were not ideal. The results on the crack500 dataset are: recall: 0.912,  precision: 0.680, f1_score: 0.758. Furthermore, the experimental results on several other datasets are also very poor. These results are quite different from those given in your paper. Please tell me why.

**Comment by lovelyyoshino** [comment]
Hello， I hope you can provide more details for the  determine  😃

XZNWU ***@***.***> 于2023年11月10日周五 19:27写道：

**Comment by XZNWU** [comment]
I used the code you provided, and the parameter settings are the same, but the results are quite different.
